title: Your Language Sucks
description: >-
  Your programming language sucks. Here is why
baseurl: ""
url: "https://yourlanguagesucks.com"
repo: https://github.com/rakshazi/yourlanguagesucks.com/
patreon: https://patreon.com/rakshazi
liberapay: https://liberapay.com/rakshazi
paypal: https://paypal.me/rakshazi
category: guide
tags: ['programming languages', 'guide']
logo:
  url: /assets/img/logo.jpg
  type: image/jpeg
poster: # because jpg does not work with transparency properly
  url: /assets/img/logo.png
  type: image/png

markdown: kramdown
sass:
    style: compressed
compress_html:
  ignore:
    envs: ['development']
  clippings: all
  comments: all
  startings: all
  endings: all
  blanklines: false
  profile: false

keep_files:
- CNAME
- assets
- favicon.ico

exclude:
- .git
- .github
- .gitignore
- .gitlab-ci.yml
- tags
- vendor
- Gemfile
- Gemfile.lock
- Makefile
- README.md
